# Generated by Django 3.2.7 on 2021-09-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_exchange_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='source',
            field=models.CharField(default='NoName', max_length=20),
        ),
    ]
