# Generated by Django 3.2.5 on 2021-07-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=60)),
                ('faculty_name', models.CharField(max_length=200)),
                ('nos', models.IntegerField(default=2)),
            ],
        ),
    ]
