# Generated by Django 3.2.6 on 2021-09-01 18:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_remove_teacher_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, region=None, unique=True),
        ),
    ]
