# Generated by Django 3.2.7 on 2021-09-28 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('email_from', models.CharField(max_length=100)),
                ('email_to', models.CharField(max_length=100)),
            ],
        ),
    ]
