# Generated by Django 3.2.6 on 2021-09-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='sent_date',
        ),
    ]
