# Generated by Django 3.2.5 on 2021-08-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='nos',
            new_name='number_of_students',
        ),
    ]
